name: CI/CD Pipeline for PHP App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
    
      - name: Deploy to Heroku
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
            heroku auth:token
            heroku git:remote -a grupo8-app  
            git push heroku master