name: CI/CD Pipeline for PHP App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuración PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  
          extensions: mbstring, ctype, xml, pdo_mysql  

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | heroku auth:token
          heroku git:remote -a grupo8-app

      - name: Deploy to Heroku
        run: |
          git push heroku master