name: CI/CD Pipeline for PHP App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuración PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  
          extensions: mbstring, ctype, xml, pdo_mysql 

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/grupo8-app.git
          git push heroku master